# Grid World 迷宮策略

|  | 1 | 2 | 3 |
|  ----  | ----  |  ----  | ----  |
| 4 | 5 | 6 | 7 |
| 8 | 9 | 10 | 11 |
|12 | 13 | 14 |  |

In [11]:
import numpy as np
import random

In [12]:
gridSize = 4     
rewardValue = -1 
terminationStates = [[0,0], [gridSize-1, gridSize-1]] 
actions = [[-1, 0], [1, 0], [0, 1], [0, -1]] 

In [18]:
def actionValue(initialPosition, action):
    if initialPosition in terminationStates:
        finalPosition = initialPosition
        reward = 0
    else:
        finalPosition = np.array(initialPosition) + np.array(action)
        reward = rewardValue
    
    if -1 in finalPosition or gridSize in finalPosition:
        finalPosition = initialPosition
        reward = rewardValue
    return finalPosition, reward

In [19]:
def policy_evaluation(numIterations, gamma, valueMap):
    valueMap1 = np.copy(valueMap)
    for i in range(numIterations):
        for state in states:
            weightedRewards = 0
            for action in actions:
                finalPosition,reward = actionValue(state,action)
                weightedRewards += 1/4 * (reward + 
                     gamma * valueMap[finalPosition[0],finalPosition[1]])# 貝爾曼方程式(Bellman Equation) V(s)
                valueMap1[state[0],state[1]] = weightedRewards
        valueMap = np.copy(valueMap1)
        print(valueMap)

In [20]:
valueMap = np.zeros((gridSize, gridSize))
states = [[i, j] for i in range(gridSize) for j in range(gridSize)]
policy_evaluation(3,1,valueMap)


[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]
[[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]
[[ 0.     -2.4375 -2.9375 -3.    ]
 [-2.4375 -2.875  -3.     -2.9375]
 [-2.9375 -3.     -2.875  -2.4375]
 [-3.     -2.9375 -2.4375  0.    ]]
